name: Update Server Pack

on:
  push:
    paths:
      - 'Edit_Server_Pack/**' # Trigger the workflow when anything changes in the Edit_Server_Pack folder

jobs:
  update-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a new zip file
        run: |
          # Clean up
          rm Server_Pack.zip
          
          # Create a temporary directory
          mkdir Server_Pack

          # Copy the contents of Edit_Server_Pack to the temporary directory
          cp -r Edit_Server_Pack/* Server_Pack/

          # Create a new zip file with only the contents of Edit_Server_Pack
          zip -r Server_Pack.zip Server_Pack

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git add -A
          git commit -m "Update Server_Pack.zip"
          git push
