name: Create Zip File
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name buffal0chip
        git config --global user.email buffal0chip521@gmail.com
        git config pull.rebase false
        git pull
        rm -f Seats_Pack.zip
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'Seats_Pack.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "new pack"
        git push --force
