name: Update Server Pack

on:
  push:
    paths:
      - 'Edit_Server_Pack/**' # Trigger the workflow when anything changes in the Edit_Server_Pack folder

jobs:
  update-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update zip
        run: |
          # Remove old zip
          rm Server_Pack.zip

          # Create a new zip file with only the contents of Edit_Server_Pack
          zip -r Server_Pack.zip Edit_Server_Pack/*

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git add -A
          git commit -m "Update Server_Pack.zip"
          git push
