name: Update Server Pack

on:
  push:
    paths:
      - 'Edit_Server_Pack/**' # Trigger the workflow when anything changes in the Edit_Server_Pack folder

jobs:
  update-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a new zip file
        run: |
          # Create a temporary directory
          mkdir temp_zip

          # Copy the contents of Edit_Server_Pack to the temporary directory
          cp -r Edit_Server_Pack/* temp_zip/

          # Create a new zip file
          zip -r Server_Pack.zip temp_zip/

          # Clean up
          rm -rf temp_zip

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git add Server_Pack.zip
          git commit -m "Update Server_Pack.zip"
          git push
