name: Create Zip File
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Zip Seats_Pack folder
      run: |
        git rev-parse --show-toplevel
        cp -R Seat_Pack New_Seats_Pack
        rm Seats_Pack.zip
        zip -r Seats_Pack.zip New_Seats_Pack
      shell: bash

    - name: Commit and push updated Zip file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update Seats_Pack.zip"
        git push
