name: Update Server_Pack.zip
on:
  workflow_dispatch:
  push:
    paths:
      - 'Edit_Server_Pack/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make zip folder
      run: |
        rm Server_Pack.zip
        cd Edit_Server_Pack
        zip -r ../Server_Pack.zip .
      shell: bash

    - name: Commit and push updated Zip file
      run: |
        git config --local user.email "buffal0chip521@gmail.com"
        git config --local user.name "buffal0chip"
        git rev-parse --show-toplevel
        git add -A
        git commit -m "Update Server_Pack.zip"
        git push
