name: Update Server_Pack.zip
on:
  push:
    paths:
      - 'assets/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "usernamehere"
        git config --global user.email "emailhere"
        git config pull.rebase false
        git pull
        rm -f Server_Pack.zip

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'Server_Pack.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig *.md'
        
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "Update Server_Pack.zip"
        git push --force
